### PR TITLE
Forget about bookdown, use rmarkdown website

### PR DESCRIPTION
**Pull request by peterdesmet**
Thanks for the tip @stijnvanhoey: let's use [RMarkdown websites](https://rmarkdown.rstudio.com/rmarkdown_websites.html). Even though I am a fan of bookdown, this is better all around: 🎉

- simpler
- more customizable
- lets an Rmd be its own thing
- very similar to pkgdown

And because @LienReyserhove and I like the whitespace in bookdown, I added a custom inbo.css that adds some (plus our pink):

screen shot 2018-02-23 at 20 56 40

### CODE REVIEW

**Comment by peterdesmet** [comment]
Merge away if you agree. 😄

**Comment by stijnvanhoey** [comment]
Earlier today, I was annoyed by the lack of whitespace when working on the [git-course](https://github.com/inbo/git-course), I'l recycle the `inbo.css` right away ;-)

**Comment by stijnvanhoey** [comment]
Oh nooo, the INBO-pink does not match my exercise panels ;-( 
image

**Comment by peterdesmet** [comment]
Nope, we’ll need a bit more css for those.

**Pull request merged**
